### ISSUE TITLE
panic: Split called after Scan

### ISSUE THREAD

**Issue by yc90s** [tiborvass/uniline#6]
when I try to execute example code, I got this error msg

```
panic: Split called after Scan [recovered]
	panic: Split called after Scan

goroutine 1 [running]:
panic(0x80ff620, 0x1840a180)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x326
github.com/tiborvass/uniline.(*Scanner).Scan.func2(0x184100e0, 0x18439f24)
	/home/ycg/goblog/src/github.com/tiborvass/uniline/uniline.go:124 +0x19c
panic(0x80ff620, 0x1840a180)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x3fd
bufio.(*Scanner).Split(0x184180c0, 0x8154870)
	/usr/lib/go-1.6/src/bufio/scan.go:271 +0x65
```

**Comment by speters** [comment]
This fixes it:
```diff
diff --git c/uniline.go w/uniline.go
index 0236d1f..fb48131 100644
--- c/uniline.go
+++ w/uniline.go
@@ -128,6 +128,11 @@ func (s *Scanner) Scan(prompt string) (more bool) {
 	// no need to initialize internal scanner more than once
 	if s.scanner == nil {
 		s.scanner = bufio.NewScanner(s.input)
+	    if s.dumb {
+		    s.scanner.Split(bufio.ScanLines)
+        } else {
+            s.scanner.Split(bufio.ScanRunes)
+        }
 	}
 
 	s.prompt = textFromString(prompt)
@@ -172,7 +177,6 @@ func (s *Scanner) Scan(prompt string) (more bool) {
 	s.history.index = len(s.history.tmp) - 1
 
 	s.output.Write(s.prompt.bytes)
-	s.scanner.Split(bufio.ScanRunes)
 
 	var p []byte
 

```


[uniline-splitpanicfix.diff.txt](https://github.com/tiborvass/uniline/files/2500980/uniline-splitpanicfix.diff.txt)
